sudo: required
services:
   - docker

before_install:
   - docker build -t test-docker-react -f Dockerfile.dev .
   
script:
   - docker run -e CI=true test-docker-react npm run test -- --coverage

language: generic 

deploy:
   provider: elesticbeanstalk
   region: "ap-southeast-1"
   app: "test-docker-react"
   env: "TestDockerReact-env"	   
   bucket_name: "elasticbeanstalk-ap-southeast-1-623278238715"
   bucket_path: "test-docker-react"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: "$AWS_SECRET_KEY"
